/**
 * Cloudflare Pages Deploy Provider
 *
 * Deploys documentation to Cloudflare Pages via:
 * 1. Wrangler CLI for project management
 * 2. Cloudflare API for DNS and domain config
 * 3. Auto-generated wrangler.toml and GitHub Actions workflow
 */

import type { DeployProvider, DeployResult, DNSRecord } from "../index.js";
import type { DeployConfig, DomainConfig } from "../../config/schema.js";
import { runTool, ToolNotFoundError } from "../../utils/cli-tools.js";

export class CloudflareProvider implements DeployProvider {
  id = "cloudflare";
  name = "Cloudflare Pages";

  async checkAuth(): Promise<{ authenticated: boolean; message: string }> {
    const token = process.env.CLOUDFLARE_API_TOKEN;
    const accountId = process.env.CLOUDFLARE_ACCOUNT_ID;

    if (token && accountId) {
      return { authenticated: true, message: "Cloudflare credentials found" };
    }

    try {
      await runTool("npx", ["wrangler", "whoami"]);
      return {
        authenticated: true,
        message: "Authenticated via Wrangler CLI",
      };
    } catch (error) {
      if (error instanceof ToolNotFoundError) {
        return { authenticated: false, message: error.message };
      }
      return {
        authenticated: false,
        message:
          "Set CLOUDFLARE_API_TOKEN and CLOUDFLARE_ACCOUNT_ID, or run `npx wrangler login`.",
      };
    }
  }

  async setupProject(
    deploy: DeployConfig,
    domain: DomainConfig
  ): Promise<{ projectId: string }> {
    const projectName = deploy.project || "docwalk-docs";

    try {
      await runTool("npx", [
        "wrangler",
        "pages",
        "project",
        "create",
        projectName,
        "--production-branch",
        "main",
      ]);
    } catch {
      // Project may already exist — that's fine
    }

    return { projectId: projectName };
  }

  async deploy(
    buildDir: string,
    deploy: DeployConfig,
    domain: DomainConfig
  ): Promise<DeployResult> {
    const projectName = deploy.project || "docwalk-docs";

    const result = await runTool("npx", [
      "wrangler",
      "pages",
      "deploy",
      buildDir,
      "--project-name",
      projectName,
    ]);

    // Parse URL from wrangler output
    const stdout = String(result.stdout ?? "");
    const urlMatch = stdout.match(/https:\/\/[^\s]+\.pages\.dev/);
    const url = urlMatch?.[0] || `https://${projectName}.pages.dev`;

    return {
      url: domain.custom
        ? `https://${domain.custom}${domain.base_path}`
        : url,
      previewUrl: url,
      provider: this.id,
      projectId: projectName,
      domain: domain.custom,
      ssl: true,
    };
  }

  async undeploy(
    deploy: DeployConfig,
    domain: DomainConfig
  ): Promise<{ success: boolean; message: string }> {
    const projectName = deploy.project || "docwalk-docs";

    try {
      await runTool("npx", [
        "wrangler",
        "pages",
        "project",
        "delete",
        projectName,
        "--yes",
      ]);
      return {
        success: true,
        message: `Cloudflare Pages project '${projectName}' has been deleted`,
      };
    } catch (error) {
      if (error instanceof ToolNotFoundError) {
        return { success: false, message: error.message };
      }
      return {
        success: false,
        message:
          `Could not delete Cloudflare Pages project '${projectName}'. ` +
          "Delete it manually from the Cloudflare dashboard.",
      };
    }
  }

  async configureDomain(
    domain: DomainConfig,
    deploy: DeployConfig
  ): Promise<{ configured: boolean; dnsRecords?: DNSRecord[] }> {
    if (!domain.custom) {
      return { configured: true };
    }

    const projectName = deploy.project || "docwalk-docs";

    try {
      await runTool("npx", [
        "wrangler",
        "pages",
        "project",
        "add-custom-domain",
        projectName,
        domain.custom,
      ]);
      return { configured: true };
    } catch {
      return {
        configured: false,
        dnsRecords: [
          {
            type: "CNAME",
            name: domain.custom.split(".")[0],
            value: `${projectName}.pages.dev`,
          },
        ],
      };
    }
  }

  async generateCIConfig(
    deploy: DeployConfig,
    domain: DomainConfig
  ): Promise<{ path: string; content: string }> {
    const projectName = deploy.project || "docwalk-docs";

    const content = `# DocWalk — Cloudflare Pages Deployment
# Auto-generated by DocWalk. Modify with care.

name: Deploy Documentation

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install DocWalk
        run: npm install -g docwalk

      - name: Install MkDocs Material
        run: pip install mkdocs-material mkdocs-minify-plugin

      - name: DocWalk Sync and Generate
        run: |
          docwalk sync
          docwalk generate

      - name: Build MkDocs
        run: mkdocs build --config-file docwalk-output/mkdocs.yml --site-dir site

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: \${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: \${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy site --project-name ${projectName}
`;

    return {
      path: ".github/workflows/docwalk-deploy.yml",
      content,
    };
  }

  async generatePreviewCIConfig(
    deploy: DeployConfig,
    domain: DomainConfig
  ): Promise<{ path: string; content: string }> {
    const projectName = deploy.project || "docwalk-docs";

    const content = `# DocWalk — PR Preview Deployment (Cloudflare Pages)
# Auto-generated by DocWalk. Deploys a preview branch on each PR.

name: PR Documentation Preview

on:
  pull_request:
    branches: [main]

jobs:
  preview:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      deployments: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install DocWalk
        run: npm install -g docwalk

      - name: Install MkDocs Material
        run: pip install mkdocs-material mkdocs-minify-plugin

      - name: DocWalk Generate
        run: docwalk generate --full

      - name: Build MkDocs
        run: mkdocs build --config-file docwalk-output/mkdocs.yml --site-dir site

      - name: Deploy Preview to Cloudflare Pages
        id: deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: \${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: \${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy site --project-name ${projectName} --branch pr-\${{ github.event.pull_request.number }}

      - name: Comment on PR
        uses: actions/github-script@v7
        with:
          script: |
            const previewUrl = \`https://pr-\${{ github.event.pull_request.number }}.${projectName}.pages.dev\`;
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: \`## Documentation Preview\\n\\nPreview deployed to: \${previewUrl}\\n\\n> _Generated by DocWalk_\`
            });
`;

    return {
      path: ".github/workflows/docwalk-preview.yml",
      content,
    };
  }
}
