/**
 * GitHub Pages Deploy Provider
 *
 * Deploys documentation to GitHub Pages via:
 * 1. Generating a GitHub Actions workflow file
 * 2. Configuring the gh-pages branch
 * 3. Setting up custom domain (CNAME)
 * 4. Auto-provisioning via GitHub API
 */

import type { DeployProvider, DeployResult, DNSRecord } from "../index.js";
import type { DeployConfig, DomainConfig } from "../../config/schema.js";
import { runTool, MKDOCS_INSTALL_CMD } from "../../utils/cli-tools.js";
import { writeFile, mkdir } from "fs/promises";
import path from "path";

export class GitHubPagesProvider implements DeployProvider {
  id = "gh-pages";
  name = "GitHub Pages";

  async checkAuth(): Promise<{ authenticated: boolean; message: string }> {
    const token = process.env.GITHUB_TOKEN || process.env.GH_TOKEN;

    if (token) {
      return { authenticated: true, message: "GitHub token found" };
    }

    try {
      await runTool("gh", ["auth", "status"]);
      return { authenticated: true, message: "Authenticated via gh CLI" };
    } catch {
      return {
        authenticated: false,
        message:
          "No GitHub authentication found. Set GITHUB_TOKEN or run `gh auth login`.",
      };
    }
  }

  async setupProject(
    deploy: DeployConfig,
    domain: DomainConfig
  ): Promise<{ projectId: string }> {
    return { projectId: deploy.project || "docs" };
  }

  async deploy(
    buildDir: string,
    deploy: DeployConfig,
    domain: DomainConfig
  ): Promise<DeployResult> {
    if (domain.custom) {
      const cnamePath = path.join(buildDir, "CNAME");
      await writeFile(cnamePath, domain.custom);
    }

    return {
      url: domain.custom
        ? `https://${domain.custom}${domain.base_path}`
        : `https://<username>.github.io/<repo>${domain.base_path}`,
      provider: this.id,
      projectId: deploy.project || "docs",
      domain: domain.custom,
      ssl: true,
    };
  }

  async undeploy(
    deploy: DeployConfig,
    domain: DomainConfig
  ): Promise<{ success: boolean; message: string }> {
    // GitHub Pages can be disabled via the API
    try {
      await runTool("gh", [
        "api",
        "--method", "DELETE",
        "repos/{owner}/{repo}/pages",
      ]);
      return {
        success: true,
        message: "GitHub Pages has been disabled for this repository",
      };
    } catch {
      return {
        success: false,
        message:
          "Could not disable GitHub Pages automatically. " +
          "Go to Settings → Pages in your repository to disable it manually.",
      };
    }
  }

  async configureDomain(
    domain: DomainConfig,
    deploy: DeployConfig
  ): Promise<{ configured: boolean; dnsRecords?: DNSRecord[] }> {
    if (!domain.custom) {
      return { configured: true };
    }

    const isSubdomain = domain.custom.split(".").length > 2;

    const dnsRecords: DNSRecord[] = isSubdomain
      ? [
          {
            type: "CNAME",
            name: domain.custom.split(".")[0],
            value: "<username>.github.io",
          },
        ]
      : [
          { type: "A", name: "@", value: "185.199.108.153" },
          { type: "A", name: "@", value: "185.199.109.153" },
          { type: "A", name: "@", value: "185.199.110.153" },
          { type: "A", name: "@", value: "185.199.111.153" },
        ];

    return { configured: false, dnsRecords };
  }

  async generateCIConfig(
    deploy: DeployConfig,
    domain: DomainConfig
  ): Promise<{ path: string; content: string }> {
    const content = `# DocWalk — GitHub Pages Deployment
# Auto-generated by DocWalk. Modify with care.

name: Deploy Documentation

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install DocWalk
        run: npm install -g docwalk

      - name: Install MkDocs Material
        run: ${MKDOCS_INSTALL_CMD}

      - name: DocWalk Sync and Generate
        run: |
          docwalk sync
          docwalk generate

      - name: Build MkDocs
        run: mkdocs build --config-file docwalk-output/mkdocs.yml --site-dir site

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

  deploy:
    environment:
      name: github-pages
      url: \${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
`;

    return {
      path: ".github/workflows/docwalk-deploy.yml",
      content,
    };
  }

  async generatePreviewCIConfig(
    deploy: DeployConfig,
    domain: DomainConfig
  ): Promise<{ path: string; content: string }> {
    const content = `# DocWalk — PR Preview Deployment
# Auto-generated by DocWalk. Builds docs on PR and posts a preview artifact link.

name: PR Documentation Preview

on:
  pull_request:
    branches: [main]

permissions:
  contents: read
  pull-requests: write

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install DocWalk
        run: npm install -g docwalk

      - name: Install MkDocs Material
        run: ${MKDOCS_INSTALL_CMD}

      - name: DocWalk Generate
        run: docwalk generate --full

      - name: Build MkDocs
        run: mkdocs build --config-file docwalk-output/mkdocs.yml --site-dir site

      - name: Upload preview artifact
        uses: actions/upload-artifact@v4
        with:
          name: docs-preview-pr-\${{ github.event.pull_request.number }}
          path: site
          retention-days: 5

      - name: Comment on PR
        uses: actions/github-script@v7
        with:
          script: |
            const runUrl = \`\${context.serverUrl}/\${context.repo.owner}/\${context.repo.repo}/actions/runs/\${context.runId}\`;
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: \`## Documentation Preview\\n\\nDocs preview built successfully.\\n\\nDownload the preview artifact from the [workflow run](\${runUrl}).\\n\\n> _Generated by DocWalk_\`
            });
`;

    return {
      path: ".github/workflows/docwalk-preview.yml",
      content,
    };
  }
}
