/**
 * GitHub Pages Deploy Provider
 *
 * Deploys documentation to GitHub Pages via:
 * 1. Generating a GitHub Actions workflow file
 * 2. Configuring the gh-pages branch
 * 3. Setting up custom domain (CNAME)
 * 4. Auto-provisioning via GitHub API
 */

import type { DeployProvider, DeployResult, DNSRecord } from "../index.js";
import type { DeployConfig, DomainConfig } from "../../config/schema.js";
import { writeFile, mkdir } from "fs/promises";
import path from "path";

export class GitHubPagesProvider implements DeployProvider {
  id = "gh-pages";
  name = "GitHub Pages";

  async checkAuth(): Promise<{ authenticated: boolean; message: string }> {
    // Check for GITHUB_TOKEN or gh CLI auth
    const token = process.env.GITHUB_TOKEN || process.env.GH_TOKEN;

    if (token) {
      return { authenticated: true, message: "GitHub token found" };
    }

    // Try gh CLI
    try {
      const { execa } = await import("execa");
      await execa("gh", ["auth", "status"]);
      return { authenticated: true, message: "Authenticated via gh CLI" };
    } catch {
      return {
        authenticated: false,
        message:
          "No GitHub authentication found. Set GITHUB_TOKEN or run `gh auth login`.",
      };
    }
  }

  async setupProject(
    deploy: DeployConfig,
    domain: DomainConfig
  ): Promise<{ projectId: string }> {
    // GitHub Pages doesn't require separate project setup
    // The repo itself is the project
    return { projectId: deploy.project || "docs" };
  }

  async deploy(
    buildDir: string,
    deploy: DeployConfig,
    domain: DomainConfig
  ): Promise<DeployResult> {
    // For GitHub Pages, deploying means:
    // 1. Write CNAME file if custom domain
    // 2. Push to gh-pages branch
    // The actual deployment happens via the generated GitHub Actions workflow

    if (domain.custom) {
      const cnamePath = path.join(buildDir, "CNAME");
      await writeFile(cnamePath, domain.custom);
    }

    return {
      url: domain.custom
        ? `https://${domain.custom}${domain.base_path}`
        : `https://<username>.github.io/<repo>${domain.base_path}`,
      provider: this.id,
      projectId: deploy.project || "docs",
      domain: domain.custom,
      ssl: true,
    };
  }

  async configureDomain(
    domain: DomainConfig,
    deploy: DeployConfig
  ): Promise<{ configured: boolean; dnsRecords?: DNSRecord[] }> {
    if (!domain.custom) {
      return { configured: true };
    }

    const isSubdomain = domain.custom.split(".").length > 2;

    const dnsRecords: DNSRecord[] = isSubdomain
      ? [
          {
            type: "CNAME",
            name: domain.custom.split(".")[0],
            value: "<username>.github.io",
          },
        ]
      : [
          { type: "A", name: "@", value: "185.199.108.153" },
          { type: "A", name: "@", value: "185.199.109.153" },
          { type: "A", name: "@", value: "185.199.110.153" },
          { type: "A", name: "@", value: "185.199.111.153" },
        ];

    return { configured: false, dnsRecords };
  }

  async generateCIConfig(
    deploy: DeployConfig,
    domain: DomainConfig
  ): Promise<{ path: string; content: string }> {
    const content = `# DocWalk — GitHub Pages Deployment
# Auto-generated by DocWalk. Modify with care.

name: Deploy Documentation

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history for git-diff sync

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install DocWalk
        run: npm install -g docwalk

      - name: Install MkDocs Material
        run: pip install mkdocs-material mkdocs-minify-plugin

      - name: DocWalk Sync & Generate
        run: |
          docwalk sync
          docwalk generate

      - name: Build MkDocs
        run: mkdocs build --config-file docwalk-output/mkdocs.yml --site-dir site

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'site'

  deploy:
    environment:
      name: github-pages
      url: \${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
`;

    return {
      path: ".github/workflows/docwalk-deploy.yml",
      content,
    };
  }
}
