/**
 * Netlify Deploy Provider
 *
 * Deploys documentation to Netlify via:
 * 1. Netlify CLI for project management and deployment
 * 2. Environment-based auth (NETLIFY_AUTH_TOKEN)
 * 3. Auto-generated GitHub Actions workflow
 */

import type { DeployProvider, DeployResult, DNSRecord } from "../index.js";
import type { DeployConfig, DomainConfig } from "../../config/schema.js";
import { runTool, ToolNotFoundError } from "../../utils/cli-tools.js";

export class NetlifyProvider implements DeployProvider {
  id = "netlify";
  name = "Netlify";

  async checkAuth(): Promise<{ authenticated: boolean; message: string }> {
    const token = process.env.NETLIFY_AUTH_TOKEN;

    if (token) {
      return { authenticated: true, message: "Netlify auth token found" };
    }

    try {
      await runTool("netlify", ["status"]);
      return {
        authenticated: true,
        message: "Authenticated via Netlify CLI",
      };
    } catch (error) {
      if (error instanceof ToolNotFoundError) {
        return { authenticated: false, message: error.message };
      }
      return {
        authenticated: false,
        message:
          "Set NETLIFY_AUTH_TOKEN or run `netlify login`.",
      };
    }
  }

  async setupProject(
    deploy: DeployConfig,
    domain: DomainConfig
  ): Promise<{ projectId: string }> {
    const projectName = deploy.project || "docwalk-docs";

    try {
      await runTool("netlify", ["sites:create", "--name", projectName]);
    } catch {
      // Site may already exist — that's fine
    }

    return { projectId: projectName };
  }

  async deploy(
    buildDir: string,
    deploy: DeployConfig,
    domain: DomainConfig
  ): Promise<DeployResult> {
    const projectName = deploy.project || "docwalk-docs";

    const result = await runTool("netlify", [
      "deploy",
      "--dir",
      buildDir,
      "--prod",
      "--site",
      projectName,
    ]);

    const stdout = String(result.stdout ?? "");
    const urlMatch = stdout.match(/https:\/\/[^\s]+\.netlify\.app/);
    const url = urlMatch?.[0] || `https://${projectName}.netlify.app`;

    return {
      url: domain.custom
        ? `https://${domain.custom}${domain.base_path}`
        : url,
      previewUrl: url,
      provider: this.id,
      projectId: projectName,
      domain: domain.custom,
      ssl: true,
    };
  }

  async undeploy(
    deploy: DeployConfig,
    domain: DomainConfig
  ): Promise<{ success: boolean; message: string }> {
    const projectName = deploy.project || "docwalk-docs";

    try {
      await runTool("netlify", [
        "sites:delete",
        "--site",
        projectName,
        "--force",
      ]);
      return {
        success: true,
        message: `Netlify site '${projectName}' has been deleted`,
      };
    } catch (error) {
      if (error instanceof ToolNotFoundError) {
        return { success: false, message: error.message };
      }
      return {
        success: false,
        message:
          `Could not delete Netlify site '${projectName}'. ` +
          "Delete it manually from the Netlify dashboard.",
      };
    }
  }

  async configureDomain(
    domain: DomainConfig,
    deploy: DeployConfig
  ): Promise<{ configured: boolean; dnsRecords?: DNSRecord[] }> {
    if (!domain.custom) {
      return { configured: true };
    }

    const projectName = deploy.project || "docwalk-docs";

    return {
      configured: false,
      dnsRecords: [
        {
          type: "CNAME",
          name: domain.custom.split(".")[0],
          value: `${projectName}.netlify.app`,
        },
      ],
    };
  }

  async generateCIConfig(
    deploy: DeployConfig,
    domain: DomainConfig
  ): Promise<{ path: string; content: string }> {
    const content = `# DocWalk — Netlify Deployment
# Auto-generated by DocWalk. Modify with care.

name: Deploy Documentation

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install DocWalk
        run: npm install -g docwalk

      - name: Install MkDocs Material
        run: pip install mkdocs-material mkdocs-minify-plugin

      - name: DocWalk Sync and Generate
        run: |
          docwalk sync
          docwalk generate

      - name: Build MkDocs
        run: mkdocs build --config-file docwalk-output/mkdocs.yml --site-dir site

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v3
        with:
          publish-dir: ./site
          production-deploy: true
          github-token: \${{ secrets.GITHUB_TOKEN }}
        env:
          NETLIFY_AUTH_TOKEN: \${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: \${{ secrets.NETLIFY_SITE_ID }}
`;

    return {
      path: ".github/workflows/docwalk-deploy.yml",
      content,
    };
  }

  async generatePreviewCIConfig(
    deploy: DeployConfig,
    domain: DomainConfig
  ): Promise<{ path: string; content: string }> {
    const content = `# DocWalk — PR Preview Deployment (Netlify)
# Auto-generated by DocWalk. Deploys a preview on each PR.

name: PR Documentation Preview

on:
  pull_request:
    branches: [main]

jobs:
  preview:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install DocWalk
        run: npm install -g docwalk

      - name: Install MkDocs Material
        run: pip install mkdocs-material mkdocs-minify-plugin

      - name: DocWalk Generate
        run: docwalk generate --full

      - name: Build MkDocs
        run: mkdocs build --config-file docwalk-output/mkdocs.yml --site-dir site

      - name: Deploy Preview to Netlify
        id: deploy
        uses: nwtgck/actions-netlify@v3
        with:
          publish-dir: ./site
          production-deploy: false
          github-token: \${{ secrets.GITHUB_TOKEN }}
          deploy-message: "PR #\${{ github.event.pull_request.number }} preview"
        env:
          NETLIFY_AUTH_TOKEN: \${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: \${{ secrets.NETLIFY_SITE_ID }}

      - name: Comment on PR
        uses: actions/github-script@v7
        with:
          script: |
            const deployUrl = '\${{ steps.deploy.outputs.deploy-url }}';
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: \`## Documentation Preview\\n\\nPreview deployed to: \${deployUrl}\\n\\n> _Generated by DocWalk_\`
            });
`;

    return {
      path: ".github/workflows/docwalk-preview.yml",
      content,
    };
  }
}
