/**
 * Vercel Deploy Provider
 *
 * Deploys documentation to Vercel via CLI/API.
 * Generates vercel.json and GitHub Actions workflow.
 */

import type { DeployProvider, DeployResult, DNSRecord } from "../index.js";
import type { DeployConfig, DomainConfig } from "../../config/schema.js";
import { runTool, ToolNotFoundError } from "../../utils/cli-tools.js";
import { writeFile } from "fs/promises";
import path from "path";

export class VercelProvider implements DeployProvider {
  id = "vercel";
  name = "Vercel";

  async checkAuth(): Promise<{ authenticated: boolean; message: string }> {
    const token = process.env.VERCEL_TOKEN;

    if (token) {
      return { authenticated: true, message: "Vercel token found" };
    }

    try {
      await runTool("npx", ["vercel", "whoami"]);
      return { authenticated: true, message: "Authenticated via Vercel CLI" };
    } catch (error) {
      if (error instanceof ToolNotFoundError) {
        return { authenticated: false, message: error.message };
      }
      return {
        authenticated: false,
        message: "Set VERCEL_TOKEN or run `npx vercel login`.",
      };
    }
  }

  async setupProject(
    deploy: DeployConfig,
    domain: DomainConfig
  ): Promise<{ projectId: string }> {
    const projectName = deploy.project || "docwalk-docs";
    return { projectId: projectName };
  }

  async deploy(
    buildDir: string,
    deploy: DeployConfig,
    domain: DomainConfig
  ): Promise<DeployResult> {
    // Generate vercel.json
    const vercelConfig = {
      version: 2,
      name: deploy.project || "docwalk-docs",
      builds: [{ src: "**", use: "@vercel/static" }],
      routes: [
        { handle: "filesystem" },
        { src: "/(.*)", dest: "/index.html" },
      ],
    };

    await writeFile(
      path.join(buildDir, "vercel.json"),
      JSON.stringify(vercelConfig, null, 2)
    );

    const args = ["vercel", "--prod", "--yes", buildDir];
    if (process.env.VERCEL_TOKEN) {
      args.push("--token", process.env.VERCEL_TOKEN);
    }

    const result = await runTool("npx", args);
    const stdout = String(result.stdout ?? "");
    const url = stdout.trim().split("\n").pop() || "";

    return {
      url: domain.custom
        ? `https://${domain.custom}${domain.base_path}`
        : url,
      previewUrl: url,
      provider: this.id,
      projectId: deploy.project || "docwalk-docs",
      domain: domain.custom,
      ssl: true,
    };
  }

  async undeploy(
    deploy: DeployConfig,
    domain: DomainConfig
  ): Promise<{ success: boolean; message: string }> {
    const projectName = deploy.project || "docwalk-docs";

    try {
      await runTool("npx", ["vercel", "rm", projectName, "--yes"]);
      return {
        success: true,
        message: `Vercel project '${projectName}' has been removed`,
      };
    } catch (error) {
      if (error instanceof ToolNotFoundError) {
        return { success: false, message: error.message };
      }
      return {
        success: false,
        message:
          `Could not remove Vercel project '${projectName}'. ` +
          "Delete it manually from the Vercel dashboard.",
      };
    }
  }

  async configureDomain(
    domain: DomainConfig,
    deploy: DeployConfig
  ): Promise<{ configured: boolean; dnsRecords?: DNSRecord[] }> {
    if (!domain.custom) return { configured: true };

    try {
      await runTool("npx", ["vercel", "domains", "add", domain.custom]);
      return { configured: true };
    } catch {
      return {
        configured: false,
        dnsRecords: [
          {
            type: "CNAME",
            name: domain.custom.split(".")[0],
            value: "cname.vercel-dns.com",
          },
        ],
      };
    }
  }

  async generateCIConfig(
    deploy: DeployConfig,
    domain: DomainConfig
  ): Promise<{ path: string; content: string }> {
    const content = `# DocWalk — Vercel Deployment
# Auto-generated by DocWalk. Modify with care.

name: Deploy Documentation

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install DocWalk
        run: npm install -g docwalk

      - name: Install MkDocs Material
        run: pip install mkdocs-material mkdocs-minify-plugin

      - name: DocWalk Sync and Generate
        run: |
          docwalk sync
          docwalk generate

      - name: Build MkDocs
        run: mkdocs build --config-file docwalk-output/mkdocs.yml --site-dir site

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: \${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: \${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: \${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: site
          vercel-args: --prod
`;

    return {
      path: ".github/workflows/docwalk-deploy.yml",
      content,
    };
  }

  async generatePreviewCIConfig(
    deploy: DeployConfig,
    domain: DomainConfig
  ): Promise<{ path: string; content: string }> {
    const content = `# DocWalk — PR Preview Deployment (Vercel)
# Auto-generated by DocWalk. Deploys a preview on each PR.

name: PR Documentation Preview

on:
  pull_request:
    branches: [main]

jobs:
  preview:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install DocWalk
        run: npm install -g docwalk

      - name: Install MkDocs Material
        run: pip install mkdocs-material mkdocs-minify-plugin

      - name: DocWalk Generate
        run: docwalk generate --full

      - name: Build MkDocs
        run: mkdocs build --config-file docwalk-output/mkdocs.yml --site-dir site

      - name: Deploy Preview to Vercel
        id: deploy
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: \${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: \${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: \${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: site

      - name: Comment on PR
        uses: actions/github-script@v7
        with:
          script: |
            const previewUrl = '\${{ steps.deploy.outputs.preview-url }}';
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: \`## Documentation Preview\\n\\nPreview deployed to: \${previewUrl}\\n\\n> _Generated by DocWalk_\`
            });
`;

    return {
      path: ".github/workflows/docwalk-preview.yml",
      content,
    };
  }
}
