/**
 * Concept Page Generator
 *
 * Generates AI-driven conceptual pages suggested by the structure advisor.
 * These are pages like "Authentication Flow", "Data Pipeline", etc.
 */

import type { AnalysisManifest, GeneratedPage } from "../../analysis/types.js";
import type { AIProvider } from "../../analysis/providers/base.js";
import type { PageSuggestion } from "../../analysis/structure-advisor.js";
import { buildContext } from "../../analysis/context-builder.js";
import { renderCitations } from "../narrative-engine.js";

/**
 * Generate a concept page from an AI structure suggestion.
 */
export async function generateConceptPage(
  suggestion: PageSuggestion,
  manifest: AnalysisManifest,
  provider: AIProvider,
  readFile: (filePath: string) => Promise<string>,
  repoUrl?: string,
  branch?: string
): Promise<GeneratedPage> {
  const targetModule = suggestion.relatedModules.length > 0
    ? manifest.modules.find((m) => m.filePath === suggestion.relatedModules[0])
    : undefined;

  const contextChunks = await buildContext({
    targetModule,
    topic: suggestion.title,
    tokenBudget: 6000,
    manifest,
    readFile,
  });

  const contextText = contextChunks
    .map((c) => `--- ${c.filePath} ---\n${c.content}`)
    .join("\n\n");

  const prompt = `Write a documentation page about "${suggestion.title}" for the ${manifest.projectMeta.name} project.

DESCRIPTION: ${suggestion.description}

RELATED FILES: ${suggestion.relatedModules.join(", ")}

SOURCE CODE CONTEXT:
${contextText}

INSTRUCTIONS:
1. Write a comprehensive page explaining this concept/feature
2. Reference specific code using [file:line] notation
3. Include code examples where helpful
4. Explain how this fits into the overall architecture
5. Write 4-8 paragraphs in Markdown format with proper headings`;

  try {
    let prose = await provider.generate(prompt, {
      maxTokens: 2048,
      temperature: 0.3,
      systemPrompt: "You are a technical documentation writer. Be thorough and reference specific code.",
    });

    // Process citations
    const citationRegex = /\[([^\]]+?):(\d+)\]/g;
    const citations: Array<{ text: string; filePath: string; line: number }> = [];
    let match;
    while ((match = citationRegex.exec(prose)) !== null) {
      citations.push({ text: match[0], filePath: match[1], line: parseInt(match[2], 10) });
    }
    prose = renderCitations(prose, citations, repoUrl, branch);

    const content = `---
title: "${suggestion.title}"
description: "${suggestion.description}"
---

# ${suggestion.title}

${prose}

---

*Generated by [DocWalk](https://docwalk.dev)*
`;

    return {
      path: `concepts/${suggestion.id}.md`,
      title: suggestion.title,
      content,
      navGroup: suggestion.navGroup,
      navOrder: suggestion.navOrder,
      audience: "developer",
    };
  } catch {
    // Fallback: minimal page
    return {
      path: `concepts/${suggestion.id}.md`,
      title: suggestion.title,
      content: `---
title: "${suggestion.title}"
---

# ${suggestion.title}

${suggestion.description}

Related files: ${suggestion.relatedModules.map((f) => `\`${f}\``).join(", ")}

---

*Generated by [DocWalk](https://docwalk.dev)*
`,
      navGroup: suggestion.navGroup,
      navOrder: suggestion.navOrder,
      audience: "developer",
    };
  }
}
