/**
 * Concept Page Generator
 *
 * Generates AI-driven conceptual pages suggested by the structure advisor.
 * These are pages like "Authentication Flow", "Data Pipeline", etc.
 * Uses the shared prompt builder for DeepWiki-quality output.
 */

import type { AnalysisManifest, GeneratedPage } from "../../analysis/types.js";
import type { AIProvider } from "../../analysis/providers/base.js";
import type { PageSuggestion } from "../../analysis/structure-advisor.js";
import { buildContext } from "../../analysis/context-builder.js";
import { renderCitations } from "../narrative-engine.js";
import { buildPagePrompt, buildPageSystemPrompt } from "../prompt-builder.js";

/**
 * Generate a concept page from an AI structure suggestion.
 */
export async function generateConceptPage(
  suggestion: PageSuggestion,
  manifest: AnalysisManifest,
  provider: AIProvider,
  readFile: (filePath: string) => Promise<string>,
  repoUrl?: string,
  branch?: string
): Promise<GeneratedPage> {
  const targetModule = suggestion.relatedModules.length > 0
    ? manifest.modules.find((m) => m.filePath === suggestion.relatedModules[0])
    : undefined;

  const contextChunks = await buildContext({
    targetModule,
    topic: suggestion.title,
    tokenBudget: 6000,
    manifest,
    readFile,
  });

  const relatedFileList = suggestion.relatedModules
    .map((f) => `- \`${f}\``)
    .join("\n");

  const pageInstructions = `CONCEPT: ${suggestion.title}
DESCRIPTION: ${suggestion.description}

RELATED FILES:
${relatedFileList}

Write a comprehensive documentation page about this concept following this structure:

1. **Overview** (1-2 paragraphs): What this concept/feature is and why it matters in the project. State the problem it solves.

2. **How It Works**: Explain the key mechanisms, algorithms, or patterns. Reference specific functions, classes, and types from the source code. Include a Mermaid diagram if the concept involves multiple interacting components.

3. **Key Components**: For each major piece involved, describe its role:
| Component | File | Purpose |
|-----------|------|---------|

4. **Usage Examples**: Show concrete code examples demonstrating how developers interact with this feature. Use actual exported APIs from the source.

5. **Integration Points**: How this concept connects to other parts of the system. What depends on it, and what it depends on.

Do NOT include a title heading (# heading) — it will be added by the template.
NEVER say "This module provides..." or "This file contains..." — describe the concept directly.
Write for developers who need to understand or modify this feature.`;

  try {
    const prompt = buildPagePrompt({
      title: suggestion.title,
      projectName: manifest.projectMeta.name,
      contextChunks,
      pageInstructions,
      sourceFiles: contextChunks.map((c) => c.filePath),
      repoUrl,
      branch,
    });

    let prose = await provider.generate(prompt, {
      maxTokens: 2048,
      temperature: 0.3,
      systemPrompt: buildPageSystemPrompt(),
    });

    // Process citations
    const citationRegex = /\[([^\]]+?):(\d+)\]/g;
    const citations: Array<{ text: string; filePath: string; line: number }> = [];
    let match;
    while ((match = citationRegex.exec(prose)) !== null) {
      citations.push({ text: match[0], filePath: match[1], line: parseInt(match[2], 10) });
    }
    const currentPagePath = `concepts/${suggestion.id}.md`;
    prose = renderCitations(prose, citations, repoUrl, branch, currentPagePath);

    const content = `---
title: "${suggestion.title}"
description: "${suggestion.description}"
---

# ${suggestion.title}

${prose}

---

*Generated by [DocWalk](https://docwalk.dev)*
`;

    return {
      path: `concepts/${suggestion.id}.md`,
      title: suggestion.title,
      content,
      navGroup: suggestion.navGroup,
      navOrder: suggestion.navOrder,
      audience: "developer",
    };
  } catch {
    // Fallback: minimal page
    return {
      path: `concepts/${suggestion.id}.md`,
      title: suggestion.title,
      content: `---
title: "${suggestion.title}"
---

# ${suggestion.title}

${suggestion.description}

Related files: ${suggestion.relatedModules.map((f) => `\`${f}\``).join(", ")}

---

*Generated by [DocWalk](https://docwalk.dev)*
`,
      navGroup: suggestion.navGroup,
      navOrder: suggestion.navOrder,
      audience: "developer",
    };
  }
}
