import path from "path";
import type { DocWalkConfig } from "../../config/schema.js";
import type { AnalysisManifest, GeneratedPage } from "../../analysis/types.js";
import { getLanguageDisplayName, type LanguageId } from "../../analysis/language-detect.js";
import { resolveProjectName, getLanguageTag, renderSymbol } from "../utils.js";

export function generateConfigurationPage(
  manifest: AnalysisManifest,
  config: DocWalkConfig
): GeneratedPage {
  const meta = manifest.projectMeta;
  const projectName = resolveProjectName(manifest);

  // Find config-pattern files
  const configModules = manifest.modules.filter((mod) => {
    const basename = path.basename(mod.filePath).toLowerCase();
    return (
      basename.includes("config") ||
      basename.includes("settings") ||
      basename.includes("schema") ||
      /\.(config|rc)\.[^.]+$/.test(basename)
    );
  });

  let configFilesSection = "";
  if (configModules.length > 0) {
    configFilesSection += `## Configuration Files\n\n`;
    configFilesSection += `| File | Language | Exports | Description |\n`;
    configFilesSection += `|------|----------|:-------:|-------------|\n`;
    for (const mod of configModules) {
      const publicSymbols = mod.symbols.filter((s) => s.exported);
      const slug = mod.filePath.replace(/\.[^.]+$/, "");
      const desc = mod.moduleDoc?.summary || "";
      configFilesSection += `| [\`${mod.filePath}\`](api/${slug}.md) | ${getLanguageDisplayName(mod.language as LanguageId)} | ${publicSymbols.length} | ${desc} |\n`;
    }
    configFilesSection += "\n";

    // Render exported symbols from config files
    for (const mod of configModules) {
      const publicSymbols = mod.symbols.filter((s) => s.exported);
      if (publicSymbols.length === 0) continue;

      const langTag = getLanguageTag(mod.language);
      configFilesSection += `### ${path.basename(mod.filePath)}\n\n`;
      configFilesSection += `Source: \`${mod.filePath}\`\n\n`;
      for (const sym of publicSymbols) {
        configFilesSection += renderSymbol(sym, langTag);
      }
    }
  } else {
    configFilesSection += `!!! note "No configuration files detected"\n    No files matching config patterns (\`*.config.*\`, \`config.*\`, \`settings.*\`, \`schema.*\`) were found in the analyzed source.\n\n`;
  }

  // Project config summary
  const langSummary = meta.languages
    .map((l) => `${getLanguageDisplayName(l.name as LanguageId)} (${l.fileCount} files)`)
    .join(", ");

  const analysisOptions = [
    `Depth: **${config.analysis.depth}**`,
    `Dependency graph: **${config.analysis.dependency_graph ? "enabled" : "disabled"}**`,
    `AI summaries: **${config.analysis.ai_summaries ? "enabled" : "disabled"}**`,
    `Changelog: **${config.analysis.changelog ? "enabled" : "disabled"}**`,
  ].join(" · ");

  const content = `---
title: Configuration
description: Configuration reference for ${projectName}
---

# Configuration

This page documents configuration schemas and settings found in **${projectName}**.

---

${configFilesSection}

---

## Project Configuration Summary

| Setting | Value |
|---------|-------|
| Languages detected | ${langSummary} |
| Total files analyzed | **${manifest.stats.totalFiles}** |
| Analysis options | ${analysisOptions} |

---

*Generated by DocWalk from commit \`${manifest.commitSha.slice(0, 8)}\`*
`;

  return {
    path: "configuration.md",
    title: "Configuration",
    content,
    navGroup: "",
    navOrder: 3,
    audience: "developer",
  };
}
