/**
 * FAQ Page Generator
 *
 * Auto-generates FAQ from project signals.
 * Audience: "user"
 */

import type { DocWalkConfig } from "../../config/schema.js";
import type { AnalysisManifest, GeneratedPage } from "../../analysis/types.js";
import type { AIProvider } from "../../analysis/providers/base.js";
import { resolveProjectName } from "../utils.js";
import { extractUserContent } from "../user-content-extractor.js";

export function generateFAQPage(
  manifest: AnalysisManifest,
  config: DocWalkConfig
): GeneratedPage {
  const projectName = resolveProjectName(manifest);
  const signals = extractUserContent(manifest);
  const sectionTitle = config.analysis.user_docs_config?.section_title || "User Guide";

  let content = `---
title: FAQ
description: Frequently asked questions about ${projectName}
---

# Frequently Asked Questions

`;

  // Generate FAQ items based on project signals
  content += `??? question "What is ${projectName}?"\n`;
  content += `    ${manifest.projectMeta.description || manifest.projectMeta.readmeDescription || `${projectName} is a ${manifest.projectMeta.languages[0]?.name || "software"} project.`}\n\n`;

  content += `??? question "What languages/technologies does ${projectName} use?"\n`;
  content += `    ${manifest.projectMeta.languages.map((l) => `${l.name} (${l.percentage}%)`).join(", ")}.\n\n`;

  if (signals.cliCommands.length > 0) {
    content += `??? question "What commands are available?"\n`;
    content += `    Available commands: ${signals.cliCommands.map((c) => `\`${c.name}\``).join(", ")}. See the [Getting Started](user-getting-started.md) guide for usage details.\n\n`;
  }

  if (signals.configOptions.length > 0) {
    content += `??? question "How do I configure ${projectName}?"\n`;
    content += `    ${projectName} has ${signals.configOptions.length} configuration options. See the [Features](features.md) page for details on each option.\n\n`;
  }

  if (signals.routes.length > 0) {
    content += `??? question "What API endpoints are available?"\n`;
    content += `    ${projectName} provides ${signals.routes.length} API endpoints. See the [Features](features.md) page for the full API reference.\n\n`;
  }

  if (manifest.projectMeta.repository) {
    content += `??? question "Where can I report bugs or request features?"\n`;
    content += `    File an issue on [GitHub](https://github.com/${manifest.projectMeta.repository}/issues).\n\n`;

    content += `??? question "How can I contribute?"\n`;
    content += `    Check the [repository](https://github.com/${manifest.projectMeta.repository}) for contribution guidelines.\n\n`;
  }

  content += `??? question "Where can I find the developer documentation?"\n`;
  content += `    See the [Developer Reference](getting-started.md) section for architecture, API reference, and source documentation.\n\n`;

  content += `---\n\n*Generated by [DocWalk](https://docwalk.dev)*\n`;

  return {
    path: "faq.md",
    title: "FAQ",
    content,
    navGroup: sectionTitle,
    navOrder: 4,
    audience: "user",
  };
}

/**
 * AI-enhanced FAQ page.
 */
export async function generateFAQPageNarrative(
  manifest: AnalysisManifest,
  config: DocWalkConfig,
  provider: AIProvider
): Promise<GeneratedPage> {
  const basePage = generateFAQPage(manifest, config);
  const projectName = resolveProjectName(manifest);
  const signals = extractUserContent(manifest);

  const contextSummary = [
    `Project: ${projectName}`,
    `Languages: ${manifest.projectMeta.languages.map((l) => l.name).join(", ")}`,
    `Files: ${manifest.stats.totalFiles}`,
    signals.cliCommands.length > 0 ? `CLI commands: ${signals.cliCommands.map((c) => c.name).join(", ")}` : "",
    signals.routes.length > 0 ? `API routes: ${signals.routes.length}` : "",
    signals.configOptions.length > 0 ? `Config options: ${signals.configOptions.length}` : "",
    signals.errorTypes.length > 0 ? `Error types: ${signals.errorTypes.map((e) => e.name).join(", ")}` : "",
    signals.readmeContent ? `README: ${signals.readmeContent.slice(0, 500)}` : "",
  ].filter(Boolean).join("\n");

  const prompt = `Generate a comprehensive FAQ page for "${projectName}" aimed at end users.

PROJECT CONTEXT:
${contextSummary}

INSTRUCTIONS:
1. Generate 8-15 frequently asked questions with detailed answers
2. Cover: what it is, installation, basic usage, configuration, troubleshooting, contributing
3. Write clear, helpful answers in plain language
4. Use MkDocs-compatible collapsible FAQ format: ??? question "Question here"
5. Include code examples in answers where helpful
6. Write in Markdown format`;

  try {
    const prose = await provider.generate(prompt, {
      maxTokens: 2048,
      temperature: 0.4,
      systemPrompt: "You write comprehensive FAQ pages for end users. Be thorough and helpful.",
    });

    return {
      ...basePage,
      content: `---
title: FAQ
description: Frequently asked questions about ${projectName}
---

# Frequently Asked Questions

${prose}

---

*Generated by [DocWalk](https://docwalk.dev)*
`,
    };
  } catch {
    return basePage;
  }
}
