/**
 * Features Page Generator
 *
 * Generates feature-by-feature documentation for end users.
 * Audience: "user"
 */

import type { DocWalkConfig } from "../../config/schema.js";
import type { AnalysisManifest, GeneratedPage } from "../../analysis/types.js";
import type { AIProvider } from "../../analysis/providers/base.js";
import { resolveProjectName } from "../utils.js";
import { extractUserContent } from "../user-content-extractor.js";

export function generateFeaturesPage(
  manifest: AnalysisManifest,
  config: DocWalkConfig
): GeneratedPage {
  const projectName = resolveProjectName(manifest);
  const signals = extractUserContent(manifest);
  const sectionTitle = config.analysis.user_docs_config?.section_title || "User Guide";

  let content = `---
title: Features
description: Feature documentation for ${projectName}
---

# Features

A comprehensive guide to everything ${projectName} can do.

`;

  // CLI commands as features
  if (signals.cliCommands.length > 0) {
    content += `---\n\n## Commands\n\n`;
    for (const cmd of signals.cliCommands) {
      content += `### \`${projectName} ${cmd.name}\`\n\n`;
      if (cmd.description) {
        content += `${cmd.description}\n\n`;
      }
      if (cmd.options && cmd.options.length > 0) {
        content += `**Options:**\n\n`;
        for (const opt of cmd.options) {
          content += `- \`--${opt}\`\n`;
        }
        content += "\n";
      }
    }
  }

  // API routes as features
  if (signals.routes.length > 0) {
    content += `---\n\n## API Endpoints\n\n`;
    for (const route of signals.routes) {
      content += `### \`${route.method} ${route.path}\`\n\n`;
      content += `${route.description || "Handles requests."}\n\n`;
    }
  }

  // Components as features
  if (signals.components.length > 0) {
    const described = signals.components.filter(c => c.description);
    const undescribed = signals.components.filter(c => !c.description);

    content += `---\n\n## Components\n\n`;

    // Described components get full sections
    for (const comp of described.slice(0, 20)) {
      content += `### ${comp.name}\n\n`;
      content += `${comp.description}\n\n`;
      if (comp.props?.length) {
        content += `**Props:** ${comp.props.map((p) => `\`${p}\``).join(", ")}\n\n`;
      }
    }

    // Undescribed components → compact table (no fake "The X component.")
    if (undescribed.length > 0) {
      content += `| Component | Props |\n|-----------|-------|\n`;
      for (const comp of undescribed.slice(0, 30)) {
        const props = comp.props?.length ? `\`${comp.props.join(", ")}\`` : "—";
        content += `| **${comp.name}** | ${props} |\n`;
      }
      content += `\n`;
    }
  }

  // Config options as features — only show if we have meaningful entries
  const usefulConfigOpts = signals.configOptions.filter((o) => o.type || o.description);
  if (usefulConfigOpts.length > 0) {
    content += `---\n\n## Configuration Options\n\n`;
    content += `| Option | Type | Default | Description |\n`;
    content += `|--------|------|---------|-------------|\n`;
    for (const opt of usefulConfigOpts.slice(0, 30)) {
      content += `| \`${opt.name}\` | ${opt.type || "—"} | ${opt.defaultValue || "—"} | ${opt.description || ""} |\n`;
    }
    content += "\n";
  }

  if (signals.cliCommands.length === 0 && signals.routes.length === 0 &&
      signals.components.length === 0 && usefulConfigOpts.length === 0) {
    content += `For detailed information about ${projectName}'s features, see the [Developer Reference](getting-started.md).\n\n`;
  }

  content += `---\n\n*Generated by [DocWalk](https://docwalk.dev)*\n`;

  return {
    path: "features.md",
    title: "Features",
    content,
    navGroup: sectionTitle,
    navOrder: 2,
    audience: "user",
  };
}

/**
 * AI-enhanced features page.
 */
export async function generateFeaturesPageNarrative(
  manifest: AnalysisManifest,
  config: DocWalkConfig,
  provider: AIProvider
): Promise<GeneratedPage> {
  const basePage = generateFeaturesPage(manifest, config);
  const projectName = resolveProjectName(manifest);
  const signals = extractUserContent(manifest);

  const featureList = [
    ...signals.cliCommands.map((c) => `Command: ${c.name} — ${c.description || ""}`),
    ...signals.routes.map((r) => `API: ${r.method} ${r.path} — ${r.description || ""}`),
    ...signals.components.slice(0, 10).map((c) => `Component: ${c.name} — ${c.description || ""}`),
  ].join("\n");

  const prompt = `Write feature documentation for "${projectName}" aimed at end users.

DETECTED FEATURES:
${featureList || "No specific features detected — describe general capabilities based on the project type."}

CONFIG OPTIONS: ${signals.configOptions.length}
LANGUAGES: ${manifest.projectMeta.languages.map((l) => l.name).join(", ")}

INSTRUCTIONS:
1. Write clear, user-friendly descriptions for each feature
2. Include practical examples of when/how to use each feature
3. Group related features together
4. Use simple language — this is for users, not developers
5. Write in Markdown with proper headings and code blocks where appropriate`;

  try {
    const prose = await provider.generate(prompt, {
      maxTokens: 2048,
      temperature: 0.4,
      systemPrompt: "You write clear feature documentation for end users.",
    });

    return {
      ...basePage,
      content: `---
title: Features
description: Feature documentation for ${projectName}
---

# Features

${prose}

---

*Generated by [DocWalk](https://docwalk.dev)*
`,
    };
  } catch {
    return basePage;
  }
}
