import path from "path";
import type { DocWalkConfig } from "../../config/schema.js";
import type { AnalysisManifest, GeneratedPage } from "../../analysis/types.js";
import type { AIProvider } from "../../analysis/providers/base.js";
import { getLanguageDisplayName, type LanguageId } from "../../analysis/language-detect.js";
import { resolveProjectName, detectPackageManager, getInstallCommand, getRunCommand, getAlternativeInstallCommands, generateDirectoryTree, groupModulesLogically } from "../utils.js";
import { generateGettingStartedNarrative, renderCitations } from "../narrative-engine.js";

export function generateGettingStartedPage(
  manifest: AnalysisManifest,
  config: DocWalkConfig
): GeneratedPage {
  const meta = manifest.projectMeta;
  const projectName = resolveProjectName(manifest);
  const archLink = config.analysis.architecture_tiers !== false ? "architecture/index.md" : "architecture.md";

  // Detect package manager from the project
  const pkgManager = detectPackageManager(manifest.modules);

  const installCmd = getInstallCommand(pkgManager);
  const altInstalls = getAlternativeInstallCommands(pkgManager);

  // Build grouped structure overview
  const modulesByGroup = groupModulesLogically(manifest.modules);
  const structureOverview = Object.entries(modulesByGroup)
    .sort(([, a], [, b]) => b.length - a.length)
    .map(([section, modules]) => {
      const files = modules.map((m) => `\`${path.basename(m.filePath)}\``).slice(0, 5).join(", ");
      return `| **${section}** | ${modules.length} | ${files}${modules.length > 5 ? " ..." : ""} |`;
    })
    .join("\n");

  const repoUrl = meta.repository?.includes("/")
    ? `https://github.com/${meta.repository}`
    : "<repository-url>";

  const readmeIntro = meta.readmeDescription
    ? `${meta.readmeDescription}\n\n---\n\n`
    : "";

  // Prerequisites as task list checkboxes
  const prerequisites = meta.languages.map((l) =>
    `- [x] ${getLanguageDisplayName(l.name as LanguageId)} development environment`
  ).join("\n");

  // Installation section — tabbed if JS project, plain otherwise
  let installSection: string;
  if (altInstalls) {
    installSection = `\`\`\`bash
# Clone the repository
git clone ${repoUrl}
cd ${projectName}
\`\`\`

${altInstalls.map((alt) => `=== "${alt.label}"\n\n    \`\`\`bash\n    ${alt.command}\n    \`\`\``).join("\n\n")}`;
  } else {
    installSection = `\`\`\`bash
# Clone the repository
git clone ${repoUrl}
cd ${projectName}

# Install dependencies
${installCmd}
\`\`\``;
  }

  const content = `---
title: Getting Started
description: Setup and installation guide for ${projectName}
---

# Getting Started

${readmeIntro}This guide covers the prerequisites, installation, and project structure for **${projectName}**.

---

## Prerequisites

${prerequisites}

---

## Installation

${installSection}

---

## Project Structure

\`\`\`text
${generateDirectoryTree(manifest.modules)}
\`\`\`

### Module Overview

| Section | Files | Key Modules |
|---------|:-----:|-------------|
${structureOverview}

---

## Entry Points

The primary entry points into the codebase:

${meta.entryPoints.map((e) => {
  const slug = e.replace(/\.[^.]+$/, "");
  const mod = manifest.modules.find((m) => m.filePath === e);
  const desc = mod?.moduleDoc?.summary || "";
  return `- **[\`${e}\`](api/${slug}.md)**${desc ? ` — ${desc}` : ""}`;
}).join("\n")}

---

## Next Steps

<div class="grid cards" markdown>

-   :material-sitemap:{ .lg .middle } **[Architecture](${archLink})**

    ---

    Understand the system design and dependency graph

-   :material-book-open-variant:{ .lg .middle } **[API Reference](index.md#api-by-section)**

    ---

    Browse the full API organized by component

</div>

---

*Auto-generated by DocWalk. Re-run \`docwalk generate\` to update.*
`;

  return {
    path: "getting-started.md",
    title: "Getting Started",
    content,
    navGroup: "",
    navOrder: 1,
    audience: "developer",
  };
}

/**
 * Generate an AI-enhanced getting started page with narrative prose.
 */
export async function generateGettingStartedPageNarrative(
  manifest: AnalysisManifest,
  config: DocWalkConfig,
  provider: AIProvider,
  readFile: (filePath: string) => Promise<string>
): Promise<GeneratedPage> {
  const basePage = generateGettingStartedPage(manifest, config);

  try {
    const narrative = await generateGettingStartedNarrative({
      provider,
      manifest,
      readFile,
    });

    const repoUrl = config.source.repo.includes("/") ? config.source.repo : undefined;
    const prose = renderCitations(narrative.prose, narrative.citations, repoUrl, config.source.branch);

    const projectName = resolveProjectName(manifest);
    const narrativeContent = `---
title: Getting Started
description: Setup and installation guide for ${projectName}
---

# Getting Started

${prose}

---

*Auto-generated by DocWalk with AI narrative. Re-run \`docwalk generate\` to update.*
`;

    return {
      ...basePage,
      content: narrativeContent,
    };
  } catch {
    return basePage;
  }
}
