import type { DocWalkConfig } from "../../config/schema.js";
import type { GeneratedPage, Insight } from "../../analysis/types.js";

export function generateInsightsPage(insights: Insight[], config: DocWalkConfig): GeneratedPage {
  const byCategory = new Map<string, Insight[]>();
  const bySeverity = { info: 0, warning: 0, critical: 0 };

  for (const insight of insights) {
    if (!byCategory.has(insight.category)) byCategory.set(insight.category, []);
    byCategory.get(insight.category)!.push(insight);
    bySeverity[insight.severity]++;
  }

  const categoryLabels: Record<string, string> = {
    documentation: "Documentation",
    architecture: "Architecture",
    "code-quality": "Code Quality",
    security: "Security",
    performance: "Performance",
  };

  const severityAdmonition: Record<string, string> = {
    critical: "danger",
    warning: "warning",
    info: "info",
  };

  let categorySections = "";
  for (const [category, catInsights] of byCategory) {
    categorySections += `## ${categoryLabels[category] || category}\n\n`;
    for (const insight of catInsights) {
      const admonType = severityAdmonition[insight.severity] || "info";
      categorySections += `!!! ${admonType} "${insight.title}"\n`;
      categorySections += `    ${insight.description}\n\n`;
      if (insight.affectedFiles.length > 0) {
        categorySections += `    **Affected files:** ${insight.affectedFiles.map((f) => `\`${f}\``).join(", ")}\n\n`;
      }
      categorySections += `    **Suggestion:** ${insight.suggestion}\n\n`;
    }
  }

  const hasAiInsights = config.analysis.insights_ai;

  const content = `---
title: Code Insights
description: Automated code quality analysis and improvement suggestions
---

# Code Insights

Automated analysis findings and improvement suggestions.

## Summary

| Severity | Count |
|----------|:-----:|
| :material-alert-circle: Critical | **${bySeverity.critical}** |
| :material-alert: Warning | **${bySeverity.warning}** |
| :material-information: Info | **${bySeverity.info}** |
| **Total** | **${insights.length}** |

---

${categorySections}
${!hasAiInsights ? `---

!!! tip "Unlock AI-Powered Insights"
    Get AI-powered architecture review, security scanning, and API design suggestions with DocWalk Pro.
` : ""}
---

*Generated by DocWalk from static analysis*
`;

  return {
    path: "insights.md",
    title: "Code Insights",
    content,
    navGroup: "",
    navOrder: 7,
    audience: "developer",
  };
}
