/**
 * Troubleshooting Page Generator
 *
 * Generates error reference + common issues documentation.
 * Audience: "user"
 */

import type { DocWalkConfig } from "../../config/schema.js";
import type { AnalysisManifest, GeneratedPage } from "../../analysis/types.js";
import type { AIProvider } from "../../analysis/providers/base.js";
import { resolveProjectName } from "../utils.js";
import { extractUserContent } from "../user-content-extractor.js";

export function generateTroubleshootingPage(
  manifest: AnalysisManifest,
  config: DocWalkConfig
): GeneratedPage {
  const projectName = resolveProjectName(manifest);
  const signals = extractUserContent(manifest);
  const sectionTitle = config.analysis.user_docs_config?.section_title || "User Guide";

  let content = `---
title: Troubleshooting
description: Common issues and solutions for ${projectName}
---

# Troubleshooting

Having trouble? Check the common issues below or see the error reference.

`;

  // Error types reference
  if (signals.errorTypes.length > 0) {
    content += `---\n\n## Error Reference\n\n`;
    for (const err of signals.errorTypes) {
      content += `### ${err.name}\n\n`;
      if (err.description) {
        content += `${err.description}\n\n`;
      }
      if (err.extends && err.extends !== "Error") {
        content += `Extends: \`${err.extends}\`\n\n`;
      }
      content += `Source: \`${err.filePath}\`\n\n`;
    }
  }

  // Common issues section (template)
  content += `---\n\n## Common Issues\n\n`;

  content += `### Installation Problems\n\n`;
  content += `If you're having trouble installing ${projectName}:\n\n`;
  content += `1. Make sure you have the required runtime installed\n`;
  content += `2. Check that your version meets the minimum requirements\n`;
  content += `3. Try clearing your package manager cache and reinstalling\n\n`;

  if (signals.configOptions.length > 0) {
    content += `### Configuration Issues\n\n`;
    content += `If ${projectName} isn't behaving as expected:\n\n`;
    content += `1. Check your configuration file for syntax errors\n`;
    content += `2. Verify all required options are set\n`;
    content += `3. Check environment variables are properly set\n\n`;
  }

  content += `### Getting Help\n\n`;
  if (manifest.projectMeta.repository) {
    content += `- File an issue: [GitHub Issues](https://github.com/${manifest.projectMeta.repository}/issues)\n`;
  }
  content += `- Check the [FAQ](faq.md) for answers to common questions\n\n`;

  content += `---\n\n*Generated by [DocWalk](https://docwalk.dev)*\n`;

  return {
    path: "troubleshooting.md",
    title: "Troubleshooting",
    content,
    navGroup: sectionTitle,
    navOrder: 3,
    audience: "user",
  };
}

/**
 * AI-enhanced troubleshooting page.
 */
export async function generateTroubleshootingPageNarrative(
  manifest: AnalysisManifest,
  config: DocWalkConfig,
  provider: AIProvider
): Promise<GeneratedPage> {
  const basePage = generateTroubleshootingPage(manifest, config);
  const projectName = resolveProjectName(manifest);
  const signals = extractUserContent(manifest);

  const errorList = signals.errorTypes
    .map((e) => `${e.name}${e.description ? `: ${e.description}` : ""}`)
    .join("\n");

  const prompt = `Write a troubleshooting guide for "${projectName}" aimed at end users.

KNOWN ERROR TYPES:
${errorList || "No custom error types detected."}

PROJECT TYPE: ${manifest.projectMeta.projectType || "unknown"}
LANGUAGES: ${manifest.projectMeta.languages.map((l) => l.name).join(", ")}
CLI COMMANDS: ${signals.cliCommands.length}
CONFIG OPTIONS: ${signals.configOptions.length}

INSTRUCTIONS:
1. Create a practical troubleshooting guide with common issues and solutions
2. For each known error type, explain what causes it and how to fix it
3. Include general troubleshooting steps (installation, configuration, runtime)
4. Add a "Getting Help" section
5. Write in a friendly, supportive tone
6. Use Markdown with proper headings, code blocks, and admonitions`;

  try {
    const prose = await provider.generate(prompt, {
      maxTokens: 2048,
      temperature: 0.3,
      systemPrompt: "You write helpful troubleshooting guides for end users. Be empathetic and solution-focused.",
    });

    return {
      ...basePage,
      content: `---
title: Troubleshooting
description: Common issues and solutions for ${projectName}
---

# Troubleshooting

${prose}

---

*Generated by [DocWalk](https://docwalk.dev)*
`,
    };
  } catch {
    return basePage;
  }
}
