import path from "path";
import type { DocWalkConfig } from "../../config/schema.js";
import type { AnalysisManifest, GeneratedPage } from "../../analysis/types.js";
import { getLanguageDisplayName, type LanguageId } from "../../analysis/language-detect.js";
import { resolveProjectName, groupModulesLogically } from "../utils.js";

export function generateUsageGuidePage(
  manifest: AnalysisManifest,
  config: DocWalkConfig
): GeneratedPage {
  const meta = manifest.projectMeta;
  const projectName = resolveProjectName(manifest);
  const modulesByGroup = groupModulesLogically(manifest.modules);
  const sectionCount = Object.keys(modulesByGroup).length;
  const archLink = config.analysis.architecture_tiers !== false ? "architecture/index.md" : "architecture.md";

  // Find the most-connected modules for quick-start links
  const connectionCounts = new Map<string, number>();
  for (const edge of manifest.dependencyGraph.edges) {
    connectionCounts.set(edge.from, (connectionCounts.get(edge.from) ?? 0) + 1);
    connectionCounts.set(edge.to, (connectionCounts.get(edge.to) ?? 0) + 1);
  }
  const topConnected = [...connectionCounts.entries()]
    .sort((a, b) => b[1] - a[1])
    .slice(0, 5);

  const primaryLang = meta.languages[0]
    ? getLanguageDisplayName(meta.languages[0].name as LanguageId)
    : "";
  const langDesc = primaryLang ? `a ${primaryLang} project` : "this project";

  const sectionList = Object.entries(modulesByGroup)
    .sort(([, a], [, b]) => b.length - a.length)
    .map(([section, modules]) => `- **${section}** — ${modules.length} module${modules.length > 1 ? "s" : ""}`)
    .join("\n");

  let keyModulesSection = "";
  if (topConnected.length > 0) {
    keyModulesSection = `### Key Modules\n\nThe most interconnected modules — good starting points:\n\n`;
    keyModulesSection += topConnected.map(([file, count]) => {
      const slug = file.replace(/\.[^.]+$/, "");
      return `- [\`${file}\`](api/${slug}.md) — ${count} connections`;
    }).join("\n");
    keyModulesSection += "\n";
  }

  const content = `---
title: Usage Guide
description: How to navigate and use the ${projectName} documentation
---

# Usage Guide

This documentation covers **${projectName}**, ${langDesc} with **${manifest.stats.totalFiles} files** across **${sectionCount} sections** and **${manifest.stats.totalSymbols} documented symbols**.

It is auto-generated by [DocWalk](https://docwalk.dev) and stays in sync with the repository.

---

## API Reference Organization

API Reference pages are grouped by logical section based on directory structure:

${sectionList}

Each module page includes:

- Module summary and metadata
- Exports table with kind badges
- Detailed API reference with signatures, parameters, and return types
- Architecture context diagram
- Dependency list (internal and external imports)

---

## Quick Start

| Page | Description |
|------|-------------|
| **[Overview](index.md)** | Project summary, statistics, and quick links |
| **[Getting Started](getting-started.md)** | Prerequisites, installation, and project structure |
| **[Architecture](${archLink})** | Dependency graph and module relationships |
${config.analysis.config_docs ? `| **[Configuration](configuration.md)** | Configuration schemas and settings reference |\n` : ""}${config.analysis.types_page ? `| **[Types & Interfaces](types.md)** | Aggregate view of all exported types |\n` : ""}${config.analysis.dependencies_page ? `| **[Dependencies](dependencies.md)** | External packages and their usage across modules |\n` : ""}${config.analysis.changelog !== false ? `| **[Changelog](changelog.md)** | Recent changes from git history |\n` : ""}
${keyModulesSection}

---

## Regenerating These Docs

To regenerate this documentation after code changes:

\`\`\`bash
npx docwalk generate
\`\`\`

DocWalk will re-analyze the codebase and rebuild all pages. For incremental updates, use:

\`\`\`bash
npx docwalk sync
\`\`\`

---

## Tips

- Use the **search** (\`/\`) to quickly find any function, class, or type by name
- **Code blocks** have a copy button — click to copy snippets
- **Collapsible sections** (marked with ►) expand for additional detail
- **Mermaid diagrams** on Architecture pages are interactive — hover for details

---

*Generated by [DocWalk](https://docwalk.dev)*
`;

  return {
    path: "guide.md",
    title: "Usage Guide",
    content,
    navGroup: "",
    navOrder: 6,
    audience: "developer",
  };
}
