/**
 * User Guide Page Generator
 *
 * Generates an overview of what the software does for end-users.
 * Audience: "user" (people who USE the software, not build it).
 */

import type { DocWalkConfig } from "../../config/schema.js";
import type { AnalysisManifest, GeneratedPage } from "../../analysis/types.js";
import type { AIProvider } from "../../analysis/providers/base.js";
import { resolveProjectName } from "../utils.js";
import { extractUserContent } from "../user-content-extractor.js";

export function generateUserGuidePage(
  manifest: AnalysisManifest,
  config: DocWalkConfig
): GeneratedPage {
  const projectName = resolveProjectName(manifest);
  const signals = extractUserContent(manifest);
  const sectionTitle = config.analysis.user_docs_config?.section_title || "User Guide";

  let content = `---
title: ${projectName} — ${sectionTitle}
description: User guide for ${projectName}
---

# ${projectName}

`;

  // Use README content if available
  if (signals.readmeContent) {
    content += `${signals.readmeContent}\n\n---\n\n`;
  } else if (manifest.projectMeta.description) {
    content += `${manifest.projectMeta.description}\n\n---\n\n`;
  } else if (manifest.projectMeta.readmeDescription) {
    content += `${manifest.projectMeta.readmeDescription}\n\n---\n\n`;
  }

  // What can you do with this software?
  content += `## What You Can Do\n\n`;

  if (signals.cliCommands.length > 0) {
    content += `### Commands\n\n`;
    content += `${projectName} provides the following commands:\n\n`;
    for (const cmd of signals.cliCommands) {
      content += `- **${cmd.name}**${cmd.description ? ` — ${cmd.description}` : ""}\n`;
    }
    content += "\n";
  }

  if (signals.routes.length > 0) {
    content += `### API Endpoints\n\n`;
    content += `| Method | Path | Description |\n`;
    content += `|--------|------|-------------|\n`;
    for (const route of signals.routes) {
      content += `| \`${route.method}\` | \`${route.path}\` | ${route.description || ""} |\n`;
    }
    content += "\n";
  }

  if (signals.components.length > 0) {
    content += `### Components\n\n`;
    for (const comp of signals.components.slice(0, 15)) {
      content += `- **${comp.name}**${comp.description ? ` — ${comp.description}` : ""}\n`;
    }
    content += "\n";
  }

  if (signals.cliCommands.length === 0 && signals.routes.length === 0 && signals.components.length === 0) {
    content += `${projectName} is a ${manifest.projectMeta.languages[0]?.name || "software"} project with ${manifest.stats.totalFiles} source files.\n\n`;
  }

  content += `---\n\n`;
  content += `## Quick Links\n\n`;
  content += `- [Getting Started](user-getting-started.md) — Install and set up ${projectName}\n`;
  content += `- [Features](features.md) — Detailed feature documentation\n`;
  content += `- [Troubleshooting](troubleshooting.md) — Common issues and solutions\n`;
  content += `- [FAQ](faq.md) — Frequently asked questions\n`;
  content += `\n---\n\n*Generated by [DocWalk](https://docwalk.dev)*\n`;

  return {
    path: "user-guide.md",
    title: sectionTitle,
    content,
    navGroup: sectionTitle,
    navOrder: 0,
    audience: "user",
  };
}

/**
 * AI-enhanced user guide page.
 */
export async function generateUserGuidePageNarrative(
  manifest: AnalysisManifest,
  config: DocWalkConfig,
  provider: AIProvider
): Promise<GeneratedPage> {
  const basePage = generateUserGuidePage(manifest, config);
  const projectName = resolveProjectName(manifest);
  const signals = extractUserContent(manifest);

  const signalsSummary = [
    signals.cliCommands.length > 0 ? `CLI commands: ${signals.cliCommands.map((c) => c.name).join(", ")}` : "",
    signals.routes.length > 0 ? `API routes: ${signals.routes.length}` : "",
    signals.components.length > 0 ? `Components: ${signals.components.map((c) => c.name).slice(0, 10).join(", ")}` : "",
    signals.configOptions.length > 0 ? `Config options: ${signals.configOptions.length}` : "",
  ].filter(Boolean).join("\n");

  const prompt = `Write a user-friendly overview page for "${projectName}". This is documentation for END USERS, not developers.

PROJECT SIGNALS:
${signalsSummary}
${signals.readmeContent ? `README: ${signals.readmeContent}` : ""}
Languages: ${manifest.projectMeta.languages.map((l) => l.name).join(", ")}

INSTRUCTIONS:
1. Explain what this software does in plain language
2. Who is it for? What problems does it solve?
3. List the main capabilities/features
4. Keep it friendly and accessible — avoid jargon
5. Write 3-5 paragraphs in Markdown format`;

  try {
    const prose = await provider.generate(prompt, {
      maxTokens: 1024,
      temperature: 0.4,
      systemPrompt: "You write clear, friendly documentation for end users. Avoid developer jargon.",
    });

    const sectionTitle = config.analysis.user_docs_config?.section_title || "User Guide";
    const content = `---
title: ${projectName} — ${sectionTitle}
description: User guide for ${projectName}
---

# ${projectName}

${prose}

---

## Quick Links

- [Getting Started](user-getting-started.md) — Install and set up ${projectName}
- [Features](features.md) — Detailed feature documentation
- [Troubleshooting](troubleshooting.md) — Common issues and solutions
- [FAQ](faq.md) — Frequently asked questions

---

*Generated by [DocWalk](https://docwalk.dev)*
`;

    return { ...basePage, content };
  } catch {
    return basePage;
  }
}
