/**
 * User Getting Started Page Generator
 *
 * Generates an end-user install + first use tutorial.
 * Audience: "user" — focuses on using the software, not developing it.
 */

import type { DocWalkConfig } from "../../config/schema.js";
import type { AnalysisManifest, GeneratedPage } from "../../analysis/types.js";
import type { AIProvider } from "../../analysis/providers/base.js";
import { resolveProjectName, detectPackageManager, getInstallCommand } from "../utils.js";
import { extractUserContent } from "../user-content-extractor.js";

export function generateUserGettingStartedPage(
  manifest: AnalysisManifest,
  config: DocWalkConfig
): GeneratedPage {
  const projectName = resolveProjectName(manifest);
  const pkgManager = detectPackageManager(manifest.modules);
  const installCmd = getInstallCommand(pkgManager);
  const signals = extractUserContent(manifest);
  const sectionTitle = config.analysis.user_docs_config?.section_title || "User Guide";

  let content = `---
title: Getting Started with ${projectName}
description: Installation and first-use guide for ${projectName}
---

# Getting Started

This guide will help you install and start using **${projectName}**.

---

## Installation

\`\`\`bash
${installCmd}
\`\`\`

`;

  // If there are CLI commands, show a quick start
  if (signals.cliCommands.length > 0) {
    content += `---\n\n## Quick Start\n\n`;
    content += `After installation, you can use the following commands:\n\n`;
    content += `| Command | Description |\n`;
    content += `|---------|-------------|\n`;
    for (const cmd of signals.cliCommands.slice(0, 10)) {
      const desc = cmd.description || "";
      content += `| \`${projectName} ${cmd.name}\` | ${desc} |\n`;
    }
    content += "\n";
  }

  // If there are routes, show how to access the API
  if (signals.routes.length > 0) {
    content += `---\n\n## API Quick Start\n\n`;
    content += `${projectName} exposes the following endpoints:\n\n`;
    for (const route of signals.routes.slice(0, 5)) {
      content += `- \`${route.method} ${route.path}\`${route.description ? ` — ${route.description}` : ""}\n`;
    }
    content += "\n";
  }

  // Configuration section if config options found — only show meaningful entries
  const usefulConfigOpts = signals.configOptions.filter((o) => o.type || o.description);
  if (usefulConfigOpts.length > 0) {
    content += `---\n\n## Configuration\n\n`;
    content += `Key configuration options:\n\n`;
    content += `| Option | Type | Description |\n`;
    content += `|--------|------|-------------|\n`;
    for (const opt of usefulConfigOpts.slice(0, 10)) {
      content += `| \`${opt.name}\` | ${opt.type || "—"} | ${opt.description || ""} |\n`;
    }
    content += "\n";
  }

  content += `---\n\n## Next Steps\n\n`;
  content += `- [Features](features.md) — Explore all features in detail\n`;
  content += `- [Troubleshooting](troubleshooting.md) — Solutions to common problems\n`;
  content += `- [FAQ](faq.md) — Frequently asked questions\n`;
  content += `\n---\n\n*Generated by [DocWalk](https://docwalk.dev)*\n`;

  return {
    path: "user-getting-started.md",
    title: "Getting Started",
    content,
    navGroup: sectionTitle,
    navOrder: 1,
    audience: "user",
  };
}

/**
 * AI-enhanced user getting started page.
 */
export async function generateUserGettingStartedPageNarrative(
  manifest: AnalysisManifest,
  config: DocWalkConfig,
  provider: AIProvider
): Promise<GeneratedPage> {
  const basePage = generateUserGettingStartedPage(manifest, config);
  const projectName = resolveProjectName(manifest);
  const signals = extractUserContent(manifest);

  const prompt = `Write a getting-started tutorial for end users of "${projectName}".

AVAILABLE COMMANDS: ${signals.cliCommands.map((c) => c.name).join(", ") || "none detected"}
AVAILABLE ROUTES: ${signals.routes.map((r) => `${r.method} ${r.path}`).join(", ") || "none detected"}
CONFIG OPTIONS: ${signals.configOptions.length}
PACKAGE MANAGER: ${manifest.projectMeta.packageManager || "unknown"}

INSTRUCTIONS:
1. Write step-by-step installation instructions
2. Show a practical "first use" walkthrough
3. Include code blocks for commands the user should run
4. Write for someone who has never used this software before
5. Be friendly and encouraging
6. Write in Markdown with proper headings`;

  try {
    const prose = await provider.generate(prompt, {
      maxTokens: 1536,
      temperature: 0.3,
      systemPrompt: "You write clear, step-by-step tutorials for end users. Use simple language.",
    });

    const sectionTitle = config.analysis.user_docs_config?.section_title || "User Guide";
    return {
      ...basePage,
      content: `---
title: Getting Started with ${projectName}
description: Installation and first-use guide for ${projectName}
---

# Getting Started

${prose}

---

## Next Steps

- [Features](features.md) — Explore all features in detail
- [Troubleshooting](troubleshooting.md) — Solutions to common problems
- [FAQ](faq.md) — Frequently asked questions

---

*Generated by [DocWalk](https://docwalk.dev)*
`,
    };
  } catch {
    return basePage;
  }
}
